version: '3.8'

services:
  backend1:
    image: arb-backend:latest
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: arb-backend-1
    ports:
      - "10001:10001"
    restart: unless-stopped

  backend2:
    image: arb-backend:latest
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: arb-backend-2
    ports:
      - "10002:10001"  # container still listens on 10001 internally
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: arb-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # host location : container location : read-only
    depends_on:
      - backend1
      - backend2
    restart: unless-stopped
