version: '3.8'

services:
  backend:
    image: arb-backend
    build:
      context: .. ## root directory of project
      dockerfile: infra/Dockerfile
    container_name: arb-backend
    ports:
      - "10001:10001"
    restart: unless-stopped